export default {
  navLoginScreen: 'Login',
  navRegister: 'Register',
  navSplachScreen: 'SplashScreen',
  navForgetPassword: 'ForgetPassword',
  navResetPassword: 'ResetPassword',
  navVerifyOtp: 'navVerifyOtp',
  navServiceRegister: 'ServiceRegister',
  navMyQueue: 'MyQueue',
  navMyServices: 'MyServices',
  navProfile: 'Profile',

  errorMobileNo: 'Please enter valid mobile number',
  errorEmail: 'Please enter valid email address',
  errorPassword: 'Please enter valid password',
  errorConfirmPassword: 'password not match as above',
  errorreTypePass: 'New password not match as above',
  errorName: 'Please enter your name',
  errorBusinessName: 'Please enter your Business name',
  errUserName: 'Enter valid username',
};
