export default {
  navLoginScreen: 'Login',
  navRegister: 'Register',
  navSplachScreen: 'SplashScreen',
  navForgetPassword: 'ForgetPassword',
  navResetPassword: 'ResetPassword',
  navVerifyOtp: 'navVerifyOtp',
  navServiceRegister: 'ServiceRegister',
  navMyQueue: 'MyQueue',
  navMyServices: 'MyServices',
  navProfile: 'Profile',

  errorMobileNo: 'Please enter valid mobile number',
  errorEmail: 'Please enter valid email address',
  errorPassword: 'Please enter valid password',
  errorConfirmPassword: 'password not match as above',
  errorreTypePass: 'New password not match as above',
  errorName: 'Please enter your name',
  errorBusinessName: 'Please enter your Business name',
  errUserName: 'Enter valid username',

  stopRequests: 'StopRequest',
  search: 'Search',
  MyQueue: 'MyQueue',
  MyServices: 'MyServices',
  Profile: 'Profile',
  mainlbl: 'mainlbl',
  txtLeave: 'txtLeave',
  Drop: 'Drop',
  Cancel: 'Cancel',
  lblArrivalTime: 'lblArrivalTime',
  Car: 'Car',
  Make: 'Make',
  Color: 'Color',
  PlateNo: 'PlateNo',
  EstServiceTime: 'EstServiceTime',
  ServiceBooked: 'ServiceBooked',
  Carwash: 'Carwash',
  CarRepair: 'CarRepair',
  Chooseyourservice: 'Chooseyourservice',
  lblCarwash: 'lblCarwash',
  lblcCarWash: 'lblcCarWash',
  lblDcarEash: 'lblDcarEash',
  lblCarService: 'lblCarService',
  Amount: 'Amount',
  EstimatedTime: 'EstimatedTime',
  AddServiceAmount: 'AddServiceAmount',
  Save: 'Save',
  Edit: 'Edit',
  Delete: 'Delete',
};
